#ifndef EXTERNAL_H_INCLUDED
#define EXTERNAL_H_INCLUDED
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <windows.h>
#include <stdint.h>
#include <conio.h>

typedef enum Color {
    BLACK = 0,
    DARKBLUE = FOREGROUND_BLUE,
    DARKGREEN = FOREGROUND_GREEN,
    DARKCYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
    DARKRED = FOREGROUND_RED,
    DARKMAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
    DARKYELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
    DARKGRAY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    GRAY = FOREGROUND_INTENSITY,
    BLUE = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
    GREEN = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
    CYAN = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
    RED = FOREGROUND_INTENSITY | FOREGROUND_RED,
    MAGENTA = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
    YELLOW = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
    WHITE = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    BACKDARKBLUE = BACKGROUND_BLUE,
    BACKDARKGREEN = BACKGROUND_GREEN,
    BACKDARKCYAN = BACKGROUND_GREEN | BACKGROUND_BLUE,
    BACKDARKRED = BACKGROUND_RED,
    BACKDARKMAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
    BACKDARKYELLOW = BACKGROUND_RED | BACKGROUND_GREEN,
    BACKDARKGRAY = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    BACKGRAY = BACKGROUND_INTENSITY,
    BACKBLUE = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
    BACKGREEN = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
    BACKCYAN = BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE,
    BACKRED = BACKGROUND_INTENSITY | BACKGROUND_RED,
    BACKMAGENTA = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
    BACKYELLOW = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
    BACKWHITE = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    CYANMAGENTA = CYAN | BACKMAGENTA
}Color;

typedef struct Entity{
    Color color;
    char c;
    int16_t y,x;
}Entity;

void SetWindowSize(int8_t width, int8_t height);
void ShowsCursor(bool visible);
void SetPosition(int16_t X, int16_t Y);
void cPrint(char c, int16_t x, int16_t y);
void sPrint(char* c, int16_t x, int16_t y);
void SetColor(int8_t ForgC);
void cColoredPrint(char c, int16_t x, int16_t y, Color color);
void sColoredPrint(char* s, int16_t x, int16_t y, Color color);
void Print(const Entity entity);

#endif
